# Generated by Django 3.2.12 on 2022-03-04 05:46

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(default=datetime.date.today, verbose_name='วันที่')),
                ('full_name', models.CharField(default='-', max_length=150, verbose_name='ชื่อผู้ป่วย')),
                ('gender', models.CharField(blank=True, choices=[('-', 'ไม่ระบุ'), ('ช', 'ชาย'), ('ญ', 'หญิง')], default='ช', max_length=2, null=True, verbose_name='เพศ')),
                ('birth_day', models.DateField(blank=True, null=True, verbose_name='วันเกิด')),
                ('person_id', models.CharField(max_length=13, unique=True, verbose_name='เลขบัตรประชาชน')),
                ('airforce_type', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ทหารประจำการ'), (8, 'นักเรียนทหาร'), (2, 'พลทหาร'), (3, 'พนง.ราชการ'), (4, 'ลูกจ้างประจำ'), (5, 'ลูกจ้างชั่วคราว'), (6, 'ครอบครัว ทอ.'), (7, 'บุคคลภายนอก')], default=0, null=True, verbose_name='ประเภทข้าราชการ')),
                ('atk_date', models.DateField(blank=True, null=True, verbose_name='วันตรวจ ATK')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม'), (4, 'ผู้ป่วยสีแดง'), (5, 'หายป่วย'), (6, 'เสียชีวิต'), (7, 'ผู้ใกล้ชิดเสี่ยงสูง'), (8, 'ผู้ใกล้ชิดปลอดเชื้อ'), (9, 'ผู้ใกล้ชิดติดเชื้อ')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน')),
                ('treatment', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'รักษาระยะห่าง'), (2, 'กักตัวอยู่บ้าน'), (3, 'กักตัวรอเตียง'), (4, 'Home Isolation'), (5, 'รพ.สนาม'), (6, 'โรงพยาบาล'), (7, 'ICU')], default=0, null=True, verbose_name='การรักษาปัจจุบัน')),
                ('mobile', models.CharField(max_length=20, verbose_name='เบอร์มือถือ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ที่อยู่ปัจจุบัน')),
                ('right_medical', models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล')),
                ('emergency_name', models.CharField(default='-', max_length=150, verbose_name='ผู้ติดต่อฉุกเฉิน')),
                ('emergency_mobile', models.CharField(blank=True, max_length=20, null=True, verbose_name='เบอร์ฉุกเฉิน')),
                ('comment', models.TextField(blank=True, default=None, null=True, verbose_name='หมายเหตุ')),
                ('data_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DataUser', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name_plural': 'ตารางผู้ป่วย [Patient]',
            },
        ),
    ]
