# Generated by Django 3.2.12 on 2022-03-05 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_auto_20220304_0641'),
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='patient',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CurrentUnit', to='UserData.unit', verbose_name='สังกัด'),
        ),
    ]
