# Generated by Django 3.2.12 on 2022-03-05 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0002_auto_20220305_1309'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], default=0, max_length=3, null=True, verbose_name='หมู่เลือด'),
        ),
        migrations.AddField(
            model_name='patient',
            name='disease',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='โรคประจำตัว'),
        ),
        migrations.AddField(
            model_name='patient',
            name='drug_allergy',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ประวัติการแพ้ยา'),
        ),
        migrations.AddField(
            model_name='patient',
            name='height',
            field=models.IntegerField(null=True, verbose_name='ส่วนสูง'),
        ),
        migrations.AddField(
            model_name='patient',
            name='rt_pcr',
            field=models.DateField(blank=True, null=True, verbose_name='วันตรวจ RT PCR'),
        ),
        migrations.AddField(
            model_name='patient',
            name='weight',
            field=models.IntegerField(null=True, verbose_name='น้ำหนัก'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_day',
            field=models.DateField(default=None, verbose_name='วันเกิด'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_mobile',
            field=models.CharField(max_length=20, verbose_name='เบอร์ฉุกเฉิน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emergency_name',
            field=models.CharField(max_length=150, verbose_name='ผู้ติดต่อฉุกเฉิน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='full_name',
            field=models.CharField(max_length=150, verbose_name='ชื่อผู้ป่วย'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (1, 'ผู้ป่วยสีเขียว'), (2, 'ผู้ป่วยสีเหลืองอ่อน'), (3, 'ผู้ป่วยสีเหลืองเข้ม')], default=0, null=True, verbose_name='สถานะผู้ป่วยปัจจุบัน'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='treatment',
            field=models.IntegerField(blank=True, choices=[(0, 'ไม่ระบุ'), (10, 'รักษาระยะห่าง'), (20, 'กักตัวอยู่บ้าน'), (30, 'กักตัวรอเตียง'), (40, 'Self Isolation'), (50, 'Home Isolation'), (60, 'รพ.สนาม'), (70, 'โรงพยาบาล'), (80, 'ICU')], default=0, null=True, verbose_name='การรักษาปัจจุบัน'),
        ),
    ]
