# Generated by Django 3.2.12 on 2022-03-06 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0005_patient_document_approve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='document_approve',
            new_name='document_approved',
        ),
    ]
