# Generated by Django 3.2.12 on 2022-03-06 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0005_alter_user_options'),
        ('Patient', '0006_rename_document_approve_patient_document_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rank',
            field=models.PositiveIntegerField(blank=True, choices=[(30101, 'พล.อ.อ.*'), (30102, 'พล.อ.อ.*หญิง'), (30211, 'พล.อ.อ.'), (30212, 'พล.อ.อ.หญิง'), (30213, 'พล.อ.'), (30221, 'พล.อ.ท.'), (30222, 'พล.อ.ท.หญิง'), (30231, 'พล.อ.ต.'), (30232, 'พล.อ.ต.หญิง'), (30301, 'น.อ.(พ)'), (30302, 'น.อ.(พ) หญิง'), (30410, 'พ.อ.'), (30411, 'น.อ.'), (30412, 'น.อ.หญิง'), (30420, 'พ.ท.'), (30421, 'น.ท.'), (30422, 'น.ท.หญิง'), (30431, 'น.ต.'), (30432, 'น.ต.หญิง'), (30511, 'ร.อ.'), (30512, 'ร.อ.หญิง'), (30521, 'ร.ท.'), (30522, 'ร.ท.หญิง'), (30531, 'ร.ต.'), (30532, 'ร.ต.หญิง'), (30541, 'กห.ส.'), (30542, 'กห.ส.หญิง'), (30611, 'พ.อ.อ.(พ)'), (30612, 'พ.อ.อ.(พ) หญิง'), (30711, 'พ.อ.อ.'), (30712, 'พ.อ.อ.หญิง'), (30721, 'พ.อ.ท.'), (30722, 'พ.อ.ท.หญิง'), (30731, 'พ.อ.ต.'), (30732, 'พ.อ.ต.หญิง'), (30811, 'จ.อ.'), (30812, 'จ.อ.หญิง'), (30821, 'จ.ท.'), (30822, 'จ.ท.หญิง'), (30831, 'จ.ต.'), (30832, 'จ.ต.หญิง'), (30841, 'กห.ป.'), (30842, 'กห.ป.หญิง'), (31411, 'น.อ.'), (31412, 'น.อ.หญิง'), (31421, 'น.ท.'), (31422, 'น.ท.หญิง'), (31431, 'น.ต.'), (31432, 'น.ต.หญิง'), (31511, 'ร.อ.'), (31512, 'ร.อ.หญิง'), (31521, 'ร.ท.'), (31522, 'ร.ท.หญิง'), (31531, 'ร.ต.'), (31532, 'ร.ต.หญิง'), (40200, 'พนง.อาวุโสหญิง'), (40201, 'พนง.อาวุโส'), (40400, 'พนง.หญิง'), (40401, 'พนง.'), (40600, 'นาย'), (40601, 'นาง'), (40602, 'น.ส.'), (0, '')], default=0, null=True, verbose_name='ยศ'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='วันเกิด'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='right_medical',
            field=models.IntegerField(choices=[(0, 'ไม่ระบุ'), (1, 'เบิกจ่ายตรง (กรมบัญชีกลาง)'), (2, 'ประกันสังคม'), (3, 'UC (สปสช.)'), (4, 'เงินสด')], default=0, null=True, verbose_name='สิทธิ์การรักษาพยาบาล'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CurrentUnit', to='UserData.unit', verbose_name='สังกัด'),
        ),
    ]
