# Generated by Django 3.2.12 on 2022-03-07 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0007_auto_20220307_0523'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='rt_pcr_place',
            field=models.DateField(blank=True, max_length=50, null=True, verbose_name='สถานที่ตรวจ RT PCR'),
        ),
    ]
