# Generated by Django 3.2.12 on 2022-03-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0008_patient_rt_pcr_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='rt_pcr_place',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='สถานที่ตรวจ RT PCR'),
        ),
    ]
