# Generated by Django 3.2.12 on 2022-03-03 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unit',
            options={'verbose_name_plural': '1. หน่วยขึ้นตรง ทอ.'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('UNIT_REQUESTER', 'UNIT_Requester'), ('UNIT_ADMIN', 'Unit_Admin'), ('UNIT_COMMANDER', 'Unit_Commander'), ('SCIENCE_ADMIN', 'Science_Admin'), ('PERSON_ADMIN', 'Person_admin')), 'verbose_name_plural': '2. ผู้ใช้งานระบบ'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='re_cal_sub_unit',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='sub_unit_list',
        ),
    ]
