# Generated by Django 3.2.12 on 2022-03-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0002_auto_20220304_0641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='current_unit',
            new_name='unit',
        ),
    ]
