# Generated by Django 3.2.12 on 2022-03-05 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0003_rename_current_unit_user_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='unit_group',
        ),
    ]
