# Generated by Django 3.2.12 on 2022-03-05 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserData', '0004_remove_unit_unit_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '2. ผู้ใช้งานระบบ'},
        ),
    ]
